apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: redis
  #To allow other pods access redis
  ports:
    - port: 6379
      targetPort: 6379
